# Workflow to publish html and js from the root of the repo
name: Publish

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@3.7.1
#         with:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
#           BRANCH: gh-pages
#           FOLDER: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
